### ISSUE TITLE
Strip newline character in transaction description

### ISSUE THREAD

**Issue by Muscaw** [c-vigo/StatementPDFImporter#2]
Hey @c-vigo , I first want to thank you for the great tool. 
This helps me quite a lot since we don't have access to CSV exports for the cashback cards.

When using the tool, I noticed that I had a transaction that had a `\n` character in it.

See the following snippet that represents the CSV output.
```
...
2021-01-01;-5.5;"GSUITE my-great-domain-name.ch,
IRELAND"
...
```

I already have a fix and can provide a PR if it's ok for you.

**Comment by c-vigo** [comment]
Hey @Muscaw !
Thanks for the feedback! Sure, go ahead!
